version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: stock_monitor_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: stock_monitor
      MYSQL_USER: stock_user
      MYSQL_PASSWORD: stock_password123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword123"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - stock_network

  # Stock Monitoring Application
  stock_monitor:
    build: .
    container_name: stock_monitor_app
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      # Database Configuration
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_DB: stock_monitor
      MARIADB_USER: stock_user
      MARIADB_PASSWORD: stock_password123
      
      # Telegram Configuration
      TELEGRAM_BOT_TOKEN: 8326726882:AAHtqkq8Nxuoeg5LeY3sRDCvnX-jE2gUzMU
      TELEGRAM_CHAT_ID: 5135065193
      
      # Application Configuration
      PYTHONUNBUFFERED: 1
      TZ: UTC
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - stock_network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: stock_monitor_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: stock_user
      PMA_PASSWORD: stock_password123
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "8080:80"
    networks:
      - stock_network

volumes:
  mariadb_data:
    driver: local

networks:
  stock_network:
    driver: bridge
